### ISSUE TITLE
Issue with Matrix

### ISSUE THREAD

**Issue by ltai0001** [jamontes/plugin.video.filmsforaction#2] opened 2021-12-26 16:36 UTC
Issue with Kodi Matrix
Says “ Video type not supported”

**Comment by jamontes** [comment] 2021-12-28 20:33
Hi Itai0001,

Many thanks for let me know.

I've found the problem is caused due to some website changes and I'll try to fix it as soon as possible on a maintenance release.

Many thanks for your help and best regards,

jamontes.

**Comment by jamontes** [comment] 2021-12-30 21:26
Hi Itai0001,

I've fixed the problem and summited the changes with PR #3823 that has been accepted and merged so the add-on will be automatically updated on your plaftform in a few days hopefully.

Best regards,

jamontes.

**Closed as completed by jamontes** 2021-12-30 21:26 UTC

**Comment by ltai0001** [comment] 2021-12-31 03:48
thanks so much working great
